local V2_TAG_NUMBER = 3

---Parse a single set of spec data from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileSpec
local function parseSpecData(decoder, state, lookup)
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progress = decoder.decodeInteger(state, 1)
	result.partition = decoder.decodeInteger(state, 1)
	result.total = decoder.decodeInteger(state, 1)
	result.rank = decoder.decodeInteger(state, 3)
	result.average = decoder.decodeFixedFloat(state, 1, 1)
	result.asp = decoder.decodeInteger(state, 2)
	result.difficulty = decoder.decodeInteger(state, 1)
	result.size = decoder.decodeInteger(state, 1)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encounters = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)

		result.encounters[id] = { kills = kills, best = best }
	end
	return result
end

---Parse a binary-encoded data string into a ProviderProfile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@return ProviderProfile|nil
local function parse(decoder, content, lookup) -- luacheck: ignore 211
	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	local result = {}

	-- user data
	result.subscriber = decoder.decodeInteger(state, 1)
	-- overall data
	result.progress = decoder.decodeInteger(state, 1)
	result.total = decoder.decodeInteger(state, 1)
	result.totalKillCount = decoder.decodeInteger(state, 2)
	result.difficulty = decoder.decodeInteger(state, 1)
	result.size = decoder.decodeInteger(state, 1)
	result.perSpec = {}

	local specCount = decoder.decodeInteger(state, 1)
	if specCount > 0 then
		result.anySpec = parseSpecData(decoder, state, lookup)

		for _i = 1, specCount - 1 do
			local spec = parseSpecData(decoder, state, lookup)
			table.insert(result.perSpec, spec)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)

	if hasMainCharacter then
		local main = {}
		main.spec = decoder.decodeString(state, lookup)
		main.average = decoder.decodeFixedFloat(state, 1, 1)
		main.progress = decoder.decodeInteger(state, 1)
		main.total = decoder.decodeInteger(state, 1)
		main.totalKillCount = decoder.decodeInteger(state, 2)
		main.difficulty = decoder.decodeInteger(state, 1)
		main.size = decoder.decodeInteger(state, 1)
		result.mainCharacter = main
	end

	return result
end
 local lookup = {'Druid-Restoration','Hunter-BeastMastery','Hunter-Marksmanship','Warrior-Fury','Warrior-Arms','Rogue-Assassination','Rogue-Subtlety','Mage-Frost','Warlock-Destruction','Warlock-Affliction','Priest-Shadow','Priest-Discipline','Evoker-Preservation','Druid-Balance','Unknown-Unknown','DeathKnight-Blood','Paladin-Retribution','Druid-Guardian','Druid-Feral','Paladin-Protection','Priest-Holy','Monk-Windwalker','Monk-Mistweaver','DemonHunter-Havoc','Shaman-Elemental','Evoker-Devastation','Shaman-Restoration','Monk-Brewmaster','DeathKnight-Unholy','Mage-Fire','DemonHunter-Vengeance',}; local provider = {region='US',realm='Sargeras',name='US',type='subscribers',zone=42,date='2025-04-02',data={Ai='Aiferian:AwEICCAABAoCAQAIAQjTBABSiO0CBAoIwQsAAAUAYcILAAAFAF3DCwAABABUxAsAAAQAV8ULAAAEAFzGCwAABABYxwsAAAQAM8gLAAACAEABAAgBCNMEAFKI7QIECgjBCwAABQBhwgsAAAUAXcMLAAAEAFTECwAABABXxQsAAAQAXMYLAAAEAFjHCwAABAAzyAsAAAIAQAA=.Aimsucks:AwECCAIABRQDAgAIAQj4CQBYICUDBAoIwQsAAAIAT8ILAAADAF/DCwAAAwBixAsAAAIAP8ULAAADAGHGCwAAAwBhxwsAAAMATsgLAAABAFwCAAgBCPgJAFggJQMECgjBCwAAAQBPwgsAAAIAX8MLAAACAGLECwAAAQA/xQsAAAMAYcYLAAADAGHHCwAAAgBOyAsAAAEAXAMABQEIuiAAOPdKAQQKBcELAAABAEjCCwAAAQBJwwsAAAEATsQLAAABACrHCwAAAQAQAA==.',Ar='Archimtiros:AwEECAsABRQDBAAEAQgWAQBd/aQBBRQEwQsAAAIAY8ILAAAEAGHDCwAABABjxAsAAAEATwQABAEIFgEAXf2kAQUUBMELAAABAGPCCwAAAwBhwwsAAAQAY8QLAAABAE8FAAIBCNgEAFWiqQAFFALBCwAAAQBVwgsAAAEAVQA=.',Ba='Babylonisus:AwEDCAkABRQDBgADAQixAwBElsUABRQDwQsAAAQAY8ILAAABADbDCwAABAA0BwADAQjuBQA4Ru8ABRQDwQsAAAIAQ8ILAAABADbDCwAAAgAvBgACAQixAwBL0cUABRQCwQsAAAIAY8MLAAACADQA.',Be='Beccastarr:AwEICBsABAoCCAAIAQhVCQBac8cCBAoIwQsAAAQAY8ILAAAEAGHDCwAABABgxAsAAAMAWMULAAAEAGLGCwAABABhxwsAAAMAN8gLAAABAFoIAAgBCFUJAFpzxwIECgjBCwAABABjwgsAAAQAYcMLAAAEAGDECwAAAwBYxQsAAAQAYsYLAAAEAGHHCwAAAwA3yAsAAAEAWgA=.Berolynn:AwEGCBEABAoAAA==.',Bl='Blizinator:AwEDCBAABRQDCQADAQgUBgBDc/8ABRQDwQsAAAYASMILAAAEAD/DCwAABgBCCQADAQgUBgBDc/8ABRQDwQsAAAQASMILAAACAD/DCwAABgBCCgACAQjwCAAzfZIABRQCwQsAAAIAN8ILAAACAC8A.Blopsamdi:AwEICBgABAoDCwAIAQjUBgBRpe4CBAoIwQsAAAQAWsILAAAEAF7DCwAABABdxAsAAAMAVcULAAADAFzGCwAAAwBIxwsAAAIAP8gLAAABADwLAAgBCNQGAFGl7gIECgjBCwAABABawgsAAAQAXsMLAAACAF3ECwAAAgBVxQsAAAIAXMYLAAACAEjHCwAAAgA/yAsAAAEAPAwABAEIySwAO8cSAQQKBMMLAAACAFTECwAAAQBDxQsAAAEAP8YLAAABABcBDABSHAMIDAAFFA==.',Bo='Boomju:AwECCAIABAoAAQ0AWA4ECAoABRQ=.',Br='Brighthaven:AwECCAMABRQDAQAIAQiXBgBMrccCBAoIwQsAAAYAYsILAAAGAGDDCwAABgBcxAsAAAUATcULAAADADvGCwAAAwBaxwsAAAIAOcgLAAABACkBAAgBCJcGAEytxwIECgjBCwAAAQBiwgsAAAEAYMMLAAACAFzECwAAAQBNxQsAAAEAO8YLAAABAFrHCwAAAQA5yAsAAAEAKQ4ABwEIoQ8AVaqwAgQKB8ELAAAFAFjCCwAABQBewwsAAAQAWsQLAAAEAFnFCwAAAgBcxgsAAAIAQ8cLAAABAEsA.',Bu='Busclock:AwEDCAMABAoAAQ8AAAAICAgABAo=.',Ca='Camnit:AwECCAYABRQDCgACAQh2BgBWwqsABRQCwQsAAAUAUsILAAABAFsKAAIBCHYGADimqwAFFALBCwAAAQAWwgsAAAEAWwkAAQEIsRYAUm5MAAUUAcELAAAEAFIA.',Ch='Chiadr:AwECCAIABAoAAQ8AAAAICAgABAo=.Chiamw:AwEICAgABAoAAA==.Chiapr:AwEHCAcABAoAAQ8AAAAICAgABAo=.Chppedliver:AwECCAUABRQCDAACAQgSDAAjwIoABRQCwQsAAAMAIcILAAACACYMAAIBCBIMACPAigAFFALBCwAAAwAhwgsAAAIAJgA=.',Da='Datwunguy:AwEBCAIABRQCDAAIAQhgAgBZkTIDBAoIwQsAAAYAWsILAAAGAF/DCwAABgBixAsAAAUAYcULAAAFAGHGCwAABABjxwsAAAQAQ8gLAAABAEYMAAgBCGACAFmRMgMECgjBCwAABgBawgsAAAYAX8MLAAAGAGLECwAABQBhxQsAAAUAYcYLAAAEAGPHCwAABABDyAsAAAEARgA=.Datwunpal:AwECCAMABAoAAQwAWZEBCAIABRQ=.',De='Deaddari:AwEICBkABAoCEAAIAQirAABhTHkDBAoIwQsAAAQAYcILAAAEAGLDCwAAAwBgxAsAAAQAY8ULAAADAGHGCwAAAwBgxwsAAAMAYcgLAAABAF8QAAgBCKsAAGFMeQMECgjBCwAABABhwgsAAAQAYsMLAAADAGDECwAABABjxQsAAAMAYcYLAAADAGDHCwAAAwBhyAsAAAEAXwA=.',Di='Divineincel:AwECCAcABRQCEQACAQhGEABW0cUABRQCwQsAAAQAWsILAAADAFIRAAIBCEYQAFbRxQAFFALBCwAABABawgsAAAMAUgA=.',Eg='Egirlalert:AwEDCAoABRQDEgADAQhJAABPzRsBBRQDwQsAAAUAXcILAAAEAEbDCwAAAQBLEgADAQhJAABPzRsBBRQDwQsAAAMAXcILAAADAEbDCwAAAQBLEwACAQhWAgBDFq0ABRQCwQsAAAIARsILAAABAD8A.',El='Eldanger:AwEICBYABAoCFAAIAQj/AwBR4+0CBAoIwQsAAAQAWsILAAAEAGDDCwAABABaxAsAAAMAScULAAADAFrGCwAAAgBWxwsAAAEAU8gLAAABACsUAAgBCP8DAFHj7QIECgjBCwAABABawgsAAAQAYMMLAAAEAFrECwAAAwBJxQsAAAMAWsYLAAACAFbHCwAAAQBTyAsAAAEAKwA=.',Ev='Evokur:AwEECAoABRQCDQAEAQgxAABYDpMBBRQEwQsAAAMAYcILAAADAEjDCwAAAwBbxAsAAAEAWg0ABAEIMQAAWA6TAQUUBMELAAADAGHCCwAAAwBIwwsAAAMAW8QLAAABAFoA.',Ga='Gabelust:AwEICBMABAoAARUAShEFCBAABRQ=.Gabeprayge:AwEFCBAABRQDFQAFAQhpAABKEZUBBRQFwQsAAAQATcILAAAEAFnDCwAABABcxAsAAAMAYsULAAABAAwVAAQBCGkAAFlhlQEFFATBCwAABABNwgsAAAQAWcMLAAAEAFzECwAAAwBiDAABAQjEDwAMz1UABRQBxQsAAAEADAA=.Gahdania:AwEBCAEABAoAAQ8AAAAGCAIABAo=.Gahdsie:AwEGCAIABAoAAA==.Gargemek:AwEGCA4ABAoAAA==.',Gi='Gigathiccqt:AwECCAIABAoAAA==.Ginjaoo:AwEDCAoABRQDFgADAQjIAgBWeDgBBRQDwQsAAAQAXsILAAADAEvDCwAAAwBZFgADAQjIAgBWeDgBBRQDwQsAAAIAXsILAAABAEvDCwAAAwBZFwACAQiLDQBD5qAABRQCwQsAAAIATcILAAACADkA.',Gr='Grillingfood:AwEICAsABAoAAQQAUX8ECA0ABRQ=.',Ha='Harlemshake:AwEDCAMABAoAAQ8AAAADCAgABAo=.Hazëy:AwEICB4ABAoCGAAIAQjeFABIO5gCBAoIwQsAAAQAU8ILAAAFAE7DCwAABQBYxAsAAAUAU8ULAAAEAFjGCwAABABGxwsAAAIALMgLAAABACcYAAgBCN4UAEg7mAIECgjBCwAABABTwgsAAAUATsMLAAAFAFjECwAABQBTxQsAAAQAWMYLAAAEAEbHCwAAAgAsyAsAAAEAJwEDAFb8AQgBAAUU.',Hy='Hydrosplash:AwEECAgABRQCGQAEAQi2AABJ938BBRQEwQsAAAIAYcILAAADAF7DCwAAAgBCxAsAAAEAJhkABAEItgAASfd/AQUUBMELAAACAGHCCwAAAwBewwsAAAIAQsQLAAABACYA.',['H�']='Häzey:AwEBCAEABRQDAwAIAQgBCQBW/IMCBAoIwQsAAAQAW8ILAAAEAFfDCwAABABhxAsAAAQAWMULAAACAFPGCwAAAgBYxwsAAAIASMgLAAABAFcCAAgBCL4XAExitwIECgjBCwAAAwBBwgsAAAMAV8MLAAADADjECwAAAwBLxQsAAAEATsYLAAABAFjHCwAAAQBIyAsAAAEAVwMABwEIAQkATYeDAgQKB8ELAAABAFvCCwAAAQBEwwsAAAEAYcQLAAABAFjFCwAAAQBTxgsAAAEAUscLAAABAB8A.',Ib='Ibdapopo:AwEDCAcABRQCAgADAQghDABFVPwABRQDwQsAAAIARsILAAACAE7DCwAAAwA7AgADAQghDABFVPwABRQDwQsAAAIARsILAAACAE7DCwAAAwA7AA==.',Ka='Kajse:AwEDCAsABRQCBQADAQgGAQBMhjABBRQDwQsAAAUAW8ILAAAEAE7DCwAAAgA7BQADAQgGAQBMhjABBRQDwQsAAAUAW8ILAAAEAE7DCwAAAgA7AA==.Kazoocanoe:AwEICAgABAoAAA==.',Ke='Keylana:AwEHCBMABAoAAA==.',Ko='Kosicreampi:AwEECAEABAoAAA==.',Ku='Kurdsu:AwEBCAEABAoAAA==.',La='Laerryn:AwEICAgABAoAAA==.Lardorable:AwEECAQABAoAAA==.',Le='Lembar:AwEICB0ABAoDFgAIAQhbCgBLLbICBAoIwQsAAAUAXsILAAAFAFjDCwAABABbxAsAAAQASMULAAAEAFfGCwAAAwBUxwsAAAMATcgLAAABAAUWAAcBCFsKAFUcsgIECgfBCwAABQBewgsAAAUAWMMLAAAEAFvECwAABABIxQsAAAQAV8YLAAADAFTHCwAAAwBNFwABAQglcAAKDS0ABAoByAsAAAEACgELAEVNAQgBAAUU.',Lo='Lockhaven:AwEECA4ABAoAAQEATK0CCAMABRQ=.',Ma='Malythrokk:AwECCAUABRQCGgACAQjECwAVFHEABRQCwQsAAAMAIsILAAACAAcaAAIBCMQLABUUcQAFFALBCwAAAwAiwgsAAAIABwA=.Marlyahunter:AwEICAgABAoAAA==.',Me='Mec:AwEDCAYABRQCBwADAQh0BQA15voABRQDwQsAAAMAR8ILAAACAFXDCwAAAQAEBwADAQh0BQA15voABRQDwQsAAAMAR8ILAAACAFXDCwAAAQAEAA==.',Mo='Moochie:AwEDCAYABRQCBgADAQgAAwAlk+gABRQDwQsAAAMAN8ILAAACAAnDCwAAAQAuBgADAQgAAwAlk+gABRQDwQsAAAMAN8ILAAACAAnDCwAAAQAuAA==.Moöse:AwEICAEABAoAAQIARVQDCAcABRQ=.',Mu='Murtag:AwEECA8ABRQDBQAEAQhYAABEtnIBBRQEwQsAAAQAW8ILAAAEACnDCwAABABSxAsAAAMAPAUABAEIWAAARLZyAQUUBMELAAAEAFvCCwAABAApwwsAAAIAUsQLAAADADwEAAEBCGIWAA7NUAAFFAHDCwAAAgAOAA==.Murtwarr:AwEICBcABAoCBQAIAQhBCwBIKl8CBAoIwQsAAAMAXcILAAADAFTDCwAAAwBcxAsAAAMATsULAAADAEfGCwAAAwBGxwsAAAMAPcgLAAACABkFAAgBCEELAEgqXwIECgjBCwAAAwBdwgsAAAMAVMMLAAADAFzECwAAAwBOxQsAAAMAR8YLAAADAEbHCwAAAwA9yAsAAAIAGQEFAES2BAgPAAUU.',My='Mycropht:AwEBCAEABRQCEQAIAQg1SAAwV/MBBAoIwQsAAAQAT8ILAAAEADrDCwAABAA/xAsAAAMAHcULAAADAAXGCwAABABKxwsAAAMANsgLAAABABURAAgBCDVIADBX8wEECgjBCwAABABPwgsAAAQAOsMLAAAEAD/ECwAAAwAdxQsAAAMABcYLAAAEAErHCwAAAwA2yAsAAAEAFQA=.Mysticfists:AwEDCAgABAoAAA==.',Ni='Nisiari:AwEICBIABAoAAA==.',Pa='Panzrr:AwEGCAsABAoAAQ8AAAAICBMABAo=.',Po='Powers:AwEICAgABAoAARsAWPUCCAQABRQ=.',Qe='Qerty:AwEDCAkABRQCDgADAQjXBABc2kYBBRQDwQsAAAUAXsILAAACAGPDCwAAAgBVDgADAQjXBABc2kYBBRQDwQsAAAUAXsILAAACAGPDCwAAAgBVAA==.',Re='Reead:AwEECAoABRQDDAAEAQhFBgAwGPUABRQEwQsAAAIALcILAAAEADfDCwAAAwBHxAsAAAEAEwwAAwEIRQYAMP71AAUUA8ILAAAEADfDCwAAAwBHxAsAAAEAExUAAQEINBQALWg8AAUUAcELAAACAC0A.',Se='Serlen:AwECCAYABRQCHAACAQj4AQBahM8ABRQCwQsAAAMAYsILAAADAFIcAAIBCPgBAFqEzwAFFALBCwAAAwBiwgsAAAMAUgA=.',Sh='Sheepdk:AwECCAIABAoAARYARjEECAsABRQ=.Sheepdruid:AwEGCAYABAoAARYARjEECAsABRQ=.Sheepqt:AwEECAsABRQDFgAEAQg2AQBGMYQBBRQEwQsAAAUAWcILAAADAFvDCwAAAgA3xAsAAAEALBYABAEINgEARjGEAQUUBMELAAACAFnCCwAAAwBbwwsAAAIAN8QLAAABACwXAAEBCIQYADllQwAFFAHBCwAAAwA5AA==.Sheepwar:AwEGCAYABAoAARYARjEECAsABRQ=.Shunky:AwEBCAEABRQDFwAIAQh0DABNZpoCBAoIwQsAAAYAYMILAAAHAF3DCwAABQBgxAsAAAQAYMULAAAEADzGCwAAAwBQxwsAAAEAEsgLAAABAEwXAAcBCHQMAFXMmgIECgfBCwAABgBgwgsAAAcAXcMLAAAFAGDECwAABABgxQsAAAMAPMYLAAACAFDICwAAAQBMFgADAQgRRgANJoMABAoDxQsAAAEAFMYLAAABAAPHCwAAAQAPAA==.',Sk='Skoldknight:AwEICBQABAoCHQAIAQh6EQBGUoMCBAoIwQsAAAMAV8ILAAADAFXDCwAAAwBLxAsAAAMAJsULAAADAGHGCwAAAgBIxwsAAAIAOcgLAAABADEdAAgBCHoRAEZSgwIECgjBCwAAAwBXwgsAAAMAVcMLAAADAEvECwAAAwAmxQsAAAMAYcYLAAACAEjHCwAAAgA5yAsAAAEAMQA=.',Sm='Smashems:AwEHCBEABAoAAA==.',Sp='Sparkidan:AwEFCAEABAoAAA==.',St='Stillerno:AwEBCAMABRQCCAAIAQisFAA43z8CBAoIwQsAAAMAWsILAAADAE7DCwAAAwBaxAsAAAMAIMULAAADAE3GCwAAAgAexwsAAAEAK8gLAAACAAoIAAgBCKwUADjfPwIECgjBCwAAAwBawgsAAAMATsMLAAADAFrECwAAAwAgxQsAAAMATcYLAAACAB7HCwAAAQAryAsAAAIACgA=.',Ta='Tahrahn:AwEGCAYABAoAAA==.Tamereth:AwEICA0ABAoAAA==.Tauntable:AwEICAgABAoAAA==.',Th='Theomag:AwEICCAABAoDCAAIAQgEAgBgs1sDBAoIwQsAAAUAYcILAAAFAGPDCwAABQBjxAsAAAUAYsULAAAEAGPGCwAAAwBhxwsAAAMAW8gLAAACAFoIAAgBCAQCAGCzWwMECgjBCwAABABhwgsAAAQAY8MLAAAEAGPECwAABABixQsAAAMAY8YLAAACAGHHCwAAAgBbyAsAAAIAWh4ABwEILxsAR5VaAgQKB8ELAAABAEzCCwAAAQBXwwsAAAEATcQLAAABACjFCwAAAQBRxgsAAAEAUccLAAABADgA.Theorior:AwEDCAEABAoAAQgAYLMICCAABAo=.',Wi='Wilferrels:AwEECAkABRQDEwAEAQjIAABBZhsBBRQEwQsAAAQAT8ILAAACADHDCwAAAgBHxAsAAAEAPRMAAwEIyAAAQsYbAQUUA8ELAAAEAE/CCwAAAgAxwwsAAAIARw4AAQEIQhYAPUZUAAUUAcQLAAABAD0A.',Wo='Worldboss:AwECCAQABRQCGwAIAQh2BgBY9fICBAoIwQsAAAQASsILAAAEAFzDCwAABABbxAsAAAQAW8ULAAAEAFLGCwAABABaxwsAAAIAX8gLAAADAFwbAAgBCHYGAFj18gIECgjBCwAABABKwgsAAAQAXMMLAAAEAFvECwAABABbxQsAAAQAUsYLAAAEAFrHCwAAAgBfyAsAAAMAXAA=.',Wy='Wyntershine:AwEGCAUABAoAAQsAIA8DCAcABRQ=.',Xa='Xathras:AwEBCAMABRQCGgAIAQjlDQA7O08CBAoIwQsAAAUAQcILAAAFAFHDCwAABQAqxAsAAAUAQsULAAAEAFnGCwAABAA9xwsAAAMAHcgLAAACACUaAAgBCOUNADs7TwIECgjBCwAABQBBwgsAAAUAUcMLAAAFACrECwAABQBCxQsAAAQAWcYLAAAEAD3HCwAAAwAdyAsAAAIAJQA=.Xauroraz:AwEICAsABAoAAA==.',Zi='Zimbzy:AwEGCAgABAoAAA==.',['Ð']='Ðayglaive:AwEBCAEABRQCHwAHAQiECwBHIS0CBAoHwQsAAAQAVMILAAAEAE3DCwAABABMxAsAAAQATMULAAACAEfGCwAAAQAzxwsAAAEAOh8ABwEIhAsARyEtAgQKB8ELAAAEAFTCCwAABABNwwsAAAQATMQLAAAEAEzFCwAAAgBHxgsAAAEAM8cLAAABADoA.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end